
require("isomorphic-fetch");
const { Client } = require("@microsoft/microsoft-graph-client");

class AuthProvider {
	getAccessToken() {
    return Promise.resolve("eyJ0eXAiOiJKV1QiLCJub25jZSI6IkdQTExxNXpXSldSRVFCc0tvN2Y2bjFDaTRUYW14ektPdUU2Ny1EZ19TX0EiLCJhbGciOiJSUzI1NiIsIng1dCI6ImFQY3R3X29kdlJPb0VOZzNWb09sSWgydGlFcyIsImtpZCI6ImFQY3R3X29kdlJPb0VOZzNWb09sSWgydGlFcyJ9.eyJhdWQiOiIwMDAwMDAwMy0wMDAwLTAwMDAtYzAwMC0wMDAwMDAwMDAwMDAiLCJpc3MiOiJodHRwczovL3N0cy53aW5kb3dzLm5ldC9mMWEwMzFhYS0wN2M0LTRmY2YtYjA3NS02YmQ4ZDA3ODExYWEvIiwiaWF0IjoxNTcyMzcyNTI5LCJuYmYiOjE1NzIzNzI1MjksImV4cCI6MTU3MjM3NjQyOSwiYWNjdCI6MCwiYWNyIjoiMSIsImFpbyI6IjQyVmdZQkJWWk5CSVNkbXJ5eW1nMGE4Nks1L0xObVhQVlliZGoyNCtxL2o2OGR0RW4zd0EiLCJhbXIiOlsicHdkIl0sImFwcF9kaXNwbGF5bmFtZSI6IkdyYXBoIGV4cGxvcmVyIHN0YWdpbmcgZnJvbnRkb29yIiwiYXBwaWQiOiIxZGZiNWY5OC1mMzYzLTRiMGYtYjYzYS04ZDIwYWRhMWU2MmQiLCJhcHBpZGFjciI6IjAiLCJmYW1pbHlfbmFtZSI6IkFkbWluaXN0cmF0b3IiLCJnaXZlbl9uYW1lIjoiTU9EIiwiaXBhZGRyIjoiMTAyLjE2Ni4xMTAuMTE0IiwibmFtZSI6Ik1PRCBBZG1pbmlzdHJhdG9yIiwib2lkIjoiZDliYjU3NjYtODc4Ni00OTRkLTkxNTUtOGZkNDM2Y2U2ODU1IiwicGxhdGYiOiIzIiwicHVpZCI6IjEwMDMwMDAwQUU1MEFBREQiLCJwd2RfZXhwIjoiMzU4NTU2IiwicHdkX3VybCI6Imh0dHBzOi8vcG9ydGFsLm1pY3Jvc29mdG9ubGluZS5jb20vQ2hhbmdlUGFzc3dvcmQuYXNweCIsInNjcCI6IkFjY2Vzc1Jldmlldy5SZWFkLkFsbCBBY2Nlc3NSZXZpZXcuUmVhZFdyaXRlLkFsbCBBZ3JlZW1lbnQuUmVhZC5BbGwgQWdyZWVtZW50LlJlYWRXcml0ZS5BbGwgQW5hbHl0aWNzLlJlYWQgQ2FsZW5kYXJzLlJlYWRXcml0ZSBDaGF0LlJlYWQgQ29udGFjdHMuUmVhZFdyaXRlIEZpbGVzLlJlYWRXcml0ZS5BbGwgTWFpbC5SZWFkV3JpdGUgTm90ZXMuUmVhZFdyaXRlLkFsbCBvcGVuaWQgUGVvcGxlLlJlYWQgcHJvZmlsZSBTaXRlcy5SZWFkV3JpdGUuQWxsIFRhc2tzLlJlYWRXcml0ZSBVc2VyLlJlYWQgVXNlci5SZWFkQmFzaWMuQWxsIFVzZXIuUmVhZFdyaXRlIGVtYWlsIiwic2lnbmluX3N0YXRlIjpbImttc2kiXSwic3ViIjoieWxqU1NxTEF3bl9iYUFuTC1lUGtDWDN1WnlaZXRsUnZyTEI2UmMtUTJ0VSIsInRpZCI6ImYxYTAzMWFhLTA3YzQtNGZjZi1iMDc1LTZiZDhkMDc4MTFhYSIsInVuaXF1ZV9uYW1lIjoiYWRtaW5ATTM2NXg5MzUyNzYub25taWNyb3NvZnQuY29tIiwidXBuIjoiYWRtaW5ATTM2NXg5MzUyNzYub25taWNyb3NvZnQuY29tIiwidXRpIjoiZ3FuZHlPQU5Za2U5cFBDV2wycE1BQSIsInZlciI6IjEuMCIsInhtc19zdCI6eyJzdWIiOiJtSnduOXk2NTNwM0V4UHp3TG1rVnhfYUVPSnZqdEZkSERaQTFWTTlWSmRJIn0sInhtc190Y2R0IjoxNTM4NDg1OTA4fQ.dbOGrKzpwIJjNUUatWGWw8d4zddjg1Ndtriq_60-HJJ0UntY1L_7ogdu7OxpLlCmfkDep4WanooAIULTDYa-g9jzup4dBpf7cbI6E-h1k1tQh9GDCc3edMD16hwqzBHmefdbKewW9wyRzHXfuJM8Ax_eQkB9ceqy7e_uwjktuvGz-5d8IbtGavz_m9SwWRkOa-AYRtRnnIwhFFEHyjwY16Y-P3oAx0yBqBRN4lS09Y8c5lhraUDLyexgzB8aCSHcgn745wONLsUka5362u84T7kTDpIDsgNQIdLCzfOY52mfv6p5zMdLPg_IVYUUNtZjw8TNsDKdVG0ibXIWqfGvRw");
	}
}

const authProvider = new AuthProvider();
Client.init = Client.initWithMiddleware;

async function runSnippet() {
  try {
    const options = {
	authProvider,
};

const client = Client.init(options);

let res = await client.api('/users')
  .get();
  
res.value.map((user) => console.log(user.displayName));
  } catch (error) {
    throw error;
  }
}

runSnippet();

module.exports = { runSnippet }
